### PR TITLE
Travis fix - almost green

### LINKED ISSUE #124: travis fails on mercurial version
2.5.2 doesn't exist, we should change it at least to 2.6.2 in the requirements

### PR DESCRIPTION
**Pull request by stardust85**
Tries to fix #124 

It all amost works, only two tests fail, because they don't find some repository or what. Any idea?

### CODE REVIEW

**Comment by stardust85** [comment]
Any update on this? I'm looking forward to the green build!

**Comment by marcinkuzminski** [comment]
Hi, sorry i'll take a look tomorrow !

**Comment by stardust85** [comment]
Any update on this? I'm already considering releasing my forked version to PYPI as a last resort...

**Comment by marcinkuzminski** [comment]
Hi, i can merge this the only failing tests are CLI, which is kind of beta stuff anyway. However i'm not going to have time to make a pypi release if that something you need.

**Comment by stardust85** [comment]
Awesome! I don't need a PYPI release in the nearest time horizon. I only need to see at least some progress. I can live with referencing this lib though git commit (as pip is able to do it :) ) This merge will also help few things:

1. working CI is a good mark for both users and contributors
2. I will not diverge too much from your master branch in my P4 branch
3. people will see that this library isn't dead

Regarding the CLI interface part of this project, I should look at it, it sounds like something I might find useful :)

Regarding the two failing tests, we can disable them and can create an issue for them, makes sense?

**Comment by marcinkuzminski** [comment]
Yes let's make them xfail, and we can check them out later.

**Comment by stardust85** [comment]
Who disable the tests? Me in my travis-fix branch, or you in master? Just asking to prevent the situation that we both do it and will have to resolve the conflicts...

**Comment by marcinkuzminski** [comment]
Could you do it in your fork and potentially even add this to this pr ?

**Comment by stardust85** [comment]
Hi. I disabled the two failing tests and all tests for 2.5, 2.6 and 2.7 finally pass! However [flakes fail](https://travis-ci.org/codeinn/vcs/jobs/110116394). I don't have much experience with flakes nor python static analyis at all. Any idea what's wrong there?

**Comment by marcinkuzminski** [comment]
not sure, did you try to run pyflakes locally ?

**Comment by stardust85** [comment]
I found that it has never worked. Nor locally, nor on your master branch. That's the reason why you have it in after_script. I tried to put it to tests, but there are problems which I'm not gonna solve in this PR (unused imports that are in fact used etc.)

So I put it back to after_script :) We can create a separate issue for static code analysis...

Gonna finally accept this PR? :)

**Comment by marcinkuzminski** [comment]
wow, nice !

**Pull request merged**
